### PR TITLE
Prevent creating chats while status-go is not ready

### LINKED ISSUE #7282: Sometimes no history is retrieved if join public chat
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes if join public chat there is no history retrieved (stable wifi connection, even if there is history, even if use "Fetch last 24 hours", on mailserver that works fine)

Found on today's 0.9.33 nightly + staging fleet or on default beta fleet and same nightly

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
last 24 h messages are shown in public chat

#### Actual behavior
[comment]: # (Describe what actually happened.)
No messages is shown for the chat (even if it has some)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

I can't reproduce it constantly but if try these steps 3-4 times you might be lucky:

1. create new account
2. add picture to profile (to allow access to Storage)
3. change fleet to staging
4. log in
5. join "status" or "status-core" chat and check if history is retrieved
If relaunch app and log in then history is retrieved fine

I don't think it's because of mailserver. When no messages were retrieved there was "mail-01.do-ams3.eth.staging" mailserver. I've killed and started the app again, other mailserver was selected and history was retrieved. Then I've manually selected "mail-01.do-ams3.eth.staging" and joined another public chat - history is retrieved fine.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33 (2019011503) status-go v0.17.11-beta.e081f3ec
* Operating System: Android 6.0.1 real Galaxy S6 device

#### Logs
For staging fleet:
[Status.log](https://github.com/status-im/status-react/files/2760435/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2760437/geth.log)

For beta fleet:
[geth.log](https://github.com/status-im/status-react/files/2760484/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2760485/Status.log)

### PR DESCRIPTION
**Pull request by cammellos**
fixes: #7282 
Disable joining chats while the system is logging you in, otherwise the db gets into a inconsistent state.
status: ready

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

**Comment by cammellos** [comment]
@hesterbruikman @errorists currently this PR disables (hides) the `+` button until the login procedure is finished.

This means that the user won't see the `+` for possibly 4/5 seconds after login (should be less generally, but could be more on slower devices), and there's no feedback.

How can this be made more acceptable?

**Comment by errorists** [comment]
@cammellos A couple of questions: can it be disabled, as in greyed out and not invisible altogether? 
Is there some performance intensive tasks involved happening in the background that would severly impact animation, why I'm asking is I'd place a spinner instead of the '+' icon for the duration of disabling the button.

**Comment by cammellos** [comment]
@errorists It can be greyed out for sure, I think a spinner is also ok, there might be some CPU intensive operations in the background, but UI should not freeze.

**Comment by errorists** [comment]
@cammellos thanks, I'll edit this post tomorrow morning with a better preview of what I mean, but basically, the button circle should use our Light Grey colour for the duration and the `+` icon should be substituted for a 24x24px spinner. This way we're communicating a state that it's temporary and something is happening in the background that's why it's not clicky :) Hiding it from plain sight and then revealing would draw too much attention and likely suggest to tap the button after appearing.

**Comment by errorists** [comment]
Attached preview, working on it I found out that the change in colour to gray is unnecessary, the spinner inside will be plenty enough

screen recording framer

**Review by mandrigin — APPROVED** [review]

**Review by rasom — APPROVED** [review]

**Comment by annadanchenko** [comment]
@cammellos can you rebase it against develop, please? tests are failing for commands in chats and it should be fixed by https://github.com/status-im/status-react/pull/7291

**Comment by annadanchenko** [comment]
@cammellos on windows build 11 I see error on start "status_im.react_native.js_dependencies.keychain.SetUsername is not a function". It does not happen on previous build 10

**Comment by jakubgs** [comment]
>`status_im.react_native.js_dependencies.keychain.SetUsername is not a function`

Actually, I've seen this error on a linux nightly today.

**Comment by annadanchenko** [comment]
> Actually, I've seen this error on a linux nightly today.

oh then I'll recheck on windows nightly too, looks like not related to PR.

Indeed, it's on Windows nightly too, reporting as a separate bug

**Comment by annadanchenko** [comment]
@cammellos can you rebase, please? https://github.com/status-im/status-react/pull/7303 is fixed, so I can try on desktop too

**Comment by cammellos** [comment]
@annadanchenko done, android still fails, that's probably to do with the docker image and licenses, @jakubgs probably will want to have a look, thanks!

**Comment by jakubgs** [comment]
Yeah, for some reason the:
```
yes | /usr/lib/android-sdk/tools/bin/sdkmanager --licenses
```
stopped working, and when I try to install stuff with `sdkmanager` I get:
```
Skipping following packages as the license is not accepted:
SDK Patch Applier v4
```
Not sure what changed.

**Comment by jakubgs** [comment]
Okay, it should be fixed now.

**Comment by cammellos** [comment]
Super, dzieki!

**Comment by annadanchenko** [comment]
@cammellos  unfortunately, solution with disabling + button will not work if use universal link. 

Steps:
1. close Status app
2. in browser open https://get.status.im/chat/public/status and tap on button Open in Status
3. sign in
4. wait - in my case nothing happens (history is not retrieved)

<blockquote><div><strong><a href="https://get.status.im/chat/public/status">Join the public chat: #status in Status</a></strong></div></blockquote>

**Comment by cammellos** [comment]
@annadanchenko ready to be tested again, universal links handling will wait until login is complete.
Thanks
