### PR TITLE
Test status-go refactoring

### PR DESCRIPTION
**Pull request by vkjr**
### Summary

This is a PR to check that `status-go` refactoring (simple renaming) didn't affect anything

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

### CODE REVIEW

**Comment by jakubgs** [comment]
These iOS build failures look like the same ones that @cammellos is seeing in #12231:
```
# github.com/status-im/status-go/vendor/golang.org/x/sys/unix
../../go/src/github.com/status-im/status-go/vendor/golang.org/x/sys/unix/syscall_darwin.go:383:45: undefined: Xucred
../../go/src/github.com/status-im/status-go/vendor/golang.org/x/sys/unix/syscall_darwin.go:384:11: undefined: Xucred
../../go/src/github.com/status-im/status-go/vendor/golang.org/x/sys/unix/syscall_darwin.go:385:21: undefined: SizeofXucred
```
We tried upgrading Go on MacOS hosts from `1.13.4` to `1.15.13` in https://github.com/status-im/infra-role-golang/commit/c49c4a21.
For now I just upgrade `macos-03`, lets see what happens in this test build:
https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12231/4/
