### ISSUE TITLE
iOS crash with 'toggleWebviewDebug is not a function' when logout 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#11297]
# Bug Report

## Problem

On iOS when logging out of account Status crashed with 'toggleWebviewDebug is not a function' error.
All fine on Android 

#### Expected behavior
No crash when logging out of account
 
#### Actual behavior
When logout on iOS:
<img width="142" alt="Screenshot 2020-10-14 at 15 49 35" src="https://user-images.githubusercontent.com/8749671/95990983-e2bc1f80-0e34-11eb-8aa9-d9fd89282b38.png">

#### Notes
Apparently regression from https://github.com/status-im/status-react/pull/11053

### Reproduction
- Open Status on iOS and create new account
- Logout

### Additional Information
- Status version: develop 1.18
- Operating System: Android and iOS
